### ISSUE TITLE
Crashes when run with a panorama

### ISSUE THREAD

**Issue by nudelauflauch** [CorentinBrtx/image-stitching#3]
Traceback (most recent call last):
  File "C:\Users\felix\Downloads\image-stitching-main\image-stitching-main\main.py", line 68, in <module>
    pair_matches: List[PairMatch] = matcher.get_pair_matches()
  File "C:\Users\felix\Downloads\image-stitching-main\image-stitching-main\src\matching\multi_images_matches.py", line 72, in get_pair_matches
    if pair_match.is_valid():
  File "C:\Users\felix\Downloads\image-stitching-main\image-stitching-main\src\matching\pair_match.py", line 95, in is_valid
    self.set_overlap()
  File "C:\Users\felix\Downloads\image-stitching-main\image-stitching-main\src\matching\pair_match.py", line 71, in set_overlap
    mask_b = cv2.warpPerspective(
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:3304: error: (-215:Assertion failed) (M0.type() == CV_32F || M0.type() == CV_64F) && M0.rows == 3 && M0.cols == 3 in function 'cv::warpPerspective'

**Comment by CorentinBrtx** [comment]
Hi, have you tried running it in debugging mode to see if the images are in a good format before beeing passed to the warpPerspective function ? 
See if this helps, it seems close to what you have : https://stackoverflow.com/questions/72907431/opencv-error-215assertion-failed-m0-type-cv-32f-m0-type-cv-64
